###
//Login:
GET http://localhost:3000/api/user/
content-type: application/json
Authorization: Basic dGVzdEBtYWlsLmNvbTp0ZXN0cGFzc3dvcmQ=

###
//Register new user:
POST http://localhost:3000/api/user/
content-type: application/json

{
    "name": "test",
    "email": "test@mail.com",
    "password": "testpassword"
}

###
//Delete account:
DELETE http://localhost:3000/api/user/4
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjA2NTkyNDYyfQ.GHjafWC-XC6Pxow2FVaulJ5XyzN03S4H4tM8EwpnEuU