###
//Login:
GET http://localhost:3000/api/user/
content-type: application/json
Authorization: Basic dGVzdEBtYWlsLmNvbTp0ZXN0cGFzc3dvcmQ=

###
//Register new user:
POST http://localhost:3000/api/user/
content-type: application/json

{
    "name": "test",
    "email": "test@mail.com",
    "password": "testpassword"
}

###
//Delete account:
DELETE http://localhost:3000/api/user/15
content-type: application/json
Authorization: Pegar token válido no Login

###
//Update user:
PUT http://localhost:3000/api/user/
content-type: application/json
Authorization: Pegar token válido no Login

{
    "id": 16,
    "name": "Api Test",
    "email": "test@api.com",
    "password": "testpassword"
}

###
//Change password:
PUT http://localhost:3000/api/user/password
content-type: application/json
Authorization: Pegar token válido no Login

{
    "user": {
        "id": 16,
        "name": "Api Test",
        "email": "test@api.com",
        "password": "testpassword"
    },
    "newPassword": "apipass"
}